[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "vapack"
version = "2024.10.16a1"
authors = [
    { name = "Ian Kerby", email = "iankerby@u.boisestate.edu" },
]
dependencies = [
    "numpy"
]

[project.scripts]
vapack = "vapack_cli:main"